# Generated by Django 3.1.1 on 2020-09-11 18:48

from django.db import migrations, models
import main.validations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200911_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[main.validations.validate_discount], verbose_name='Discount'),
        ),
    ]
