# Generated by Django 3.1.1 on 2020-09-11 19:08

import django.core.validators
from django.db import migrations, models
import main.validations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200911_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_productname', message='Product name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020, validators=[main.validations.validate_product_year], verbose_name='Year'),
        ),
    ]
