# Generated by Django 3.1.1 on 2020-09-11 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200911_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_categoryname', message='Category name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_countryname', message='Country name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_companytname', message='Company name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='User name must be Alphanumerical', regex='^[a-zA-Z0-9\\s_-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_addressname', message='Address name must be Alphabetic', regex='^[a-zA-Z0-9\\s_-]*$')], verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cityname', message='City name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_countryname', message='Country name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_statename', message='State name must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_zipcodename', message='Zipcode name must be Alphabetic', regex='(^\\d{5}$)|(^\\d{5}-\\d{4}$)')], verbose_name='Zipcode'),
        ),
    ]
