# Generated by Django 3.1.1 on 2020-09-18 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200911_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_categoryname', message='Category must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_countryname', message='Country must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_productname', message='Product name must be Alphabetic', regex='^[a-zA-Z\\s0-9._-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_addressname', message='Address must be Alphanumerical', regex='^[a-zA-Z0-9/\\s_-]*$')], verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cityname', message='City must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_countryname', message='Country must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_statename', message='State must be Alphabetic', regex='^[a-zA-Z\\s_-]*$')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_zipcodename', message='Zipcode must contains 5 digits', regex='(^\\d{5}$)|(^\\d{5}-\\d{4}$)')], verbose_name='Zipcode'),
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
