# Generated by Django 3.1.1 on 2020-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200918_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Product Gallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='shortSpecifications',
            field=models.TextField(max_length=3000, null=True, verbose_name='Specifications'),
        ),
    ]
