# Generated by Django 3.1.1 on 2020-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200919_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shortSpecifications',
            field=models.TextField(max_length=200, null=True, verbose_name='Short specifications'),
        ),
    ]
