# Generated by Django 3.1.1 on 2020-09-20 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200919_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='', verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_productname', message='Product name must be Alphabetic', regex='^[a-zA-Z0-9/\\s)(._-]*$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortSpecifications',
            field=models.TextField(max_length=500, null=True, verbose_name='Short specifications'),
        ),
    ]
