# Generated by Django 3.1.1 on 2020-09-25 13:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200920_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=main.models.upload_path),
        ),
    ]
