# Generated by Django 3.1.1 on 2020-09-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200927_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
