# Generated by Django 3.1.1 on 2020-10-18 21:39

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200928_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_addressname', message='Address must be Alphanumerical', regex="^[a-zA-Z0-9',./\\s_-]*$")], verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_statename', message='State must be Alphabetic', regex="^[a-zA-Z'\\s_-]*$")], verbose_name='State'),
        ),
    ]
