# Generated by Django 3.1.1 on 2020-11-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201019_0039'),
        ('main', '0021_auto_20200928_2139'),
    ]

    operations = [
    ]
