# Generated by Django 3.1.1 on 2020-11-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20201105_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
    ]
