# Generated by Django 3.1.1 on 2020-11-06 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_20201106_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='User name must be Alphanumerical', regex='^[a-zA-Z0-9\\s_-]*$')], verbose_name='Name'),
        ),
    ]
