# Generated by Django 3.1.1 on 2020-11-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_post_country'),
        ('main', '0029_auto_20201106_1644'),
    ]

    operations = [
    ]
